arkusz: main.o menu.o tablica.o cell.o
	g++ main.o menu.o tablica.o cell.o -o arkusz

menu.o: menu.cpp
	g++ -c menu.cpp

tablica.o: tablica.cpp
	g++ -c tablica.cpp

cell.o: cell.cpp
	g++ -c cell.cpp

main.o: main.cpp
	g++ -c main.cpp

