arkusz: main.o menu.o tablica.o tablica_wysw.o
	g++ main.o menu.o tablica.o tablica_wysw.o -o arkusz

menu.o: menu.cpp
	g++ -c menu.cpp

tablica.o: tablica.cpp
	g++ -c tablica.cpp

tablica_wysw.o: tablica_wysw.cpp
	g++ -c tablica_wysw.cpp

main.o: main.cpp
	g++ -c main.cpp

